services:
  aegisir:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./aegisir/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./aegisir/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./aegisir/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"

